on: push
name: Elm review
jobs:
  elm_review:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - name: Add elm-review, elm and elm-format to path
        run: yarn bin >> $GITHUB_PATH
      - run: ls 
      - uses: sparksp/elm-review-action@v1
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
