on: push
name: Elm review
jobs:
  elm_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - name: Add elm-review to path
        run: yarn bin >> $GITHUB_PATH
      - uses: sparksp/elm-review-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
